# Generated by Django 5.1.7 on 2025-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Enter a Font Awesome icon class, e.g. 'fa fa-female'", max_length=50, null=True),
        ),
    ]
